package uk.co.mpcontracting.rpmjukebox.event;

public enum Event {

  // Application Events
  APPLICATION_INITIALISED,
  NEW_VERSION_AVAILABLE,
  DATA_INDEXED,
  MUTE_UPDATED,
  TIME_UPDATED,
  BUFFER_UPDATED,
  EQUALIZER_UPDATED,
  MEDIA_PLAYING,
  MEDIA_PAUSED,
  MEDIA_STOPPED,
  END_OF_MEDIA,
  PLAYLIST_CREATED,
  PLAYLIST_DELETED,
  PLAYLIST_CONTENT_UPDATED,
  PLAYLIST_SELECTED,
  TRACK_SELECTED,
  TRACK_QUEUED_FOR_PLAYING,

  // Menu Events
  MENU_FILE_IMPORT_PLAYLIST,
  MENU_FILE_EXPORT_PLAYLIST,
  MENU_FILE_SETTINGS,
  MENU_EDIT_ADD_PLAYLIST,
  MENU_EDIT_DELETE_PLAYLIST,
  MENU_EDIT_CREATE_PLAYLIST_FROM_ALBUM,
  MENU_EDIT_RANDOM_PLAYLIST,
  MENU_CONTROLS_PLAY_PAUSE,
  MENU_CONTROLS_PREVIOUS,
  MENU_CONTROLS_NEXT,
  MENU_CONTROLS_SHUFFLE,
  MENU_CONTROLS_REPEAT,
  MENU_CONTROLS_VOLUME_UP,
  MENU_CONTROLS_VOLUME_DOWN,
  MENU_CONTROLS_VOLUME_MUTE,
  MENU_VIEW_EQUALIZER,

  // Test Events
  TEST_EVENT
}
