package uk.co.mpcontracting.rpmjukebox.event;

public enum Event {
	APPLICATION_INITIALISED,
    EQ_BUTTON_CLICKED,
    TIME_UPDATED, 
    VOLUME_UPDATED,
    EQUALIZER_UPDATED,
    BUFFER_UPDATED,
    MEDIA_PLAYING, 
    MEDIA_PAUSED, 
    MEDIA_STOPPED,
    END_OF_MEDIA,
    PLAYLIST_CREATED,
    PLAYLIST_DELETED,
    PLAYLIST_CONTENT_UPDATED,
    UPDATE_VISIBLE_PLAYLIST;
}
